language: generic
sudo: required
dist: trusty
git:
  submodules: false
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
  global:
  - EMACS_DIR="$HOME/emacs"
  - EMACS="$HOME/emacs/src/emacs"
before_install:
  # You generally don't want 'x' in your own projects, but for the
  # purposes of actually developing `build-emacs', it's useful
  # information to have.  See the example for how you *should* be
  # doing all this!
- bash -ex build-emacs
install:
- make install
script:
- make test                     # test uncompiled
- make compile                  # test compilation
- make test                     # test compiled
