language: generic
sudo: required
dist: trusty
git:
  submodules: false
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
  global:
  - EMACS_INSTALL_DESTINATION="$HOME/emacs"
  - EMACS="$HOME/emacs/bin/emacs"
before_install:
- bash -e <(curl -fsSkL https://raw.githubusercontent.com/vermiculus/emake.el/test-install/install-emacs)
install:
- make install
script:
- make test                     # test uncompiled
- make compile                  # test compilation
- make test                     # test compiled
